extends: 
  - "eslint-config-airbnb"
parser: "babel-eslint"
plugins: 
  - react
env:
  browser: true
  es6: true
globals: 
  _: false
  it: true
rules: 
  "react/jsx-one-expression-per-line": 0
  "react/forbid-prop-types": 0
  "react/require-default-props": 0
  "class-methods-use-this": 0
  "react/prop-types": 0
  "import/prefer-default-export": 0
  "no-case-declarations": 0
  "react/destructuring-assignment": 0
  "template-curly-spacing": 0
  "no-console": 0
  indent: 0
  "no-return-assign": 0
  "no-param-reassign": 0
  "no-shadow": 0
  "no-script-url": 0
  "jsx-a11y/anchor-is-valid": 0
  "no-use-before-define": 0
  "jsx-a11y/label-has-for": 0
  "react/no-did-update-set-state": 0
  "react/no-multi-comp": 0
  "no-plusplus": 0
  "jsx-a11y/click-events-have-key-events": 0
  "jsx-a11y/no-static-element-interactions": 0
  "react/no-find-dom-node": 0
  "react/prefer-stateless-function": 0
  "import/no-extraneous-dependencies": 0
  "object-curly-newline": 0
  "max-len": 0
  "no-continue": 0
  "react/sort-comp": 0
  "no-unused-expressions": 0
  "no-unused-vars": 1
  "no-mixed-operators": 0
  "implicit-arrow-linebreak": 0
  "no-underscore-dangle": 0
settings:
  import/resolver: 
    webpack:
      config: 'scripts/config/resolve.js'